// DOM Elements
export const DOM = {
    header: document.getElementById('app-header'),
    setupScreen: document.getElementById('setup-screen'),
    quizScreen: document.getElementById('quiz-screen'),
    startQuizBtn: document.getElementById('start-quiz-btn'),
    backToSetupBtn: document.getElementById('back-to-setup-btn'),
    quizCounter: document.getElementById('quiz-counter'),
    quizId: document.getElementById('quiz-id'),
    quizImageContainer: document.getElementById('quiz-image-container'),
    quizImage: document.getElementById('quiz-image'),
    quizQuestionText: document.getElementById('quiz-question-text'),
    quizAnswers: document.getElementById('quiz-answers'),
    prevBtn: document.getElementById('prev-btn'),
    nextBtn: document.getElementById('next-btn'),
    filterModal: document.getElementById('filter-modal'),
    openFilterBtn: document.getElementById('open-filter-btn'),
    closeFilterBtn: document.getElementById('close-filter-btn'),
    applyFilterBtn: document.getElementById('apply-filter-btn'),
    selectAllBtn: document.getElementById('select-all-btn'),
    deselectAllBtn: document.getElementById('deselect-all-btn'),
    filterTree: document.getElementById('filter-tree'),
    resetCacheBtn: document.getElementById('reset-cache-btn'),
}
